DELETE FROM market_wizard;
DELETE FROM nt_zy_sale_annual_plan;
DELETE FROM nt_zy_sale_annual_plan_line;
DELETE FROM sale_order;
DELETE FROM sale_order_line;
DELETE FROM contract_management;
DELETE FROM contract_goods_line;
DELETE FROM nt_zy_sale_total_annual_quantity;
DELETE FROM nt_zy_sale_total_annual_quantity_history;
DELETE FROM nt_zy_sale_sale_market;
DELETE FROM nt_zy_sale_sale_market_line;
DELETE FROM department_monthly_work;
DELETE FROM work_task;
DELETE FROM monthly_sale_plan;
DELETE FROM monthly_sale_plan_line;
DELETE FROM production_plan;
DELETE FROM production_plan_line;
DELETE FROM mail_message WHERE model like 'work.task';
DELETE FROM mail_message WHERE model like 'contract.management';
DELETE FROM mail_message WHERE model like 'material.requirements';
DELETE FROM mail_message WHERE model like 'monthly.sale.plan';
DELETE FROM mail_message WHERE model like 'monthly.sale.plan.record';
DELETE FROM mail_message WHERE model like 'monthly.sale.plan.line';
DELETE FROM mail_message WHERE model like 'monthly.sale.plan.line.record';
DELETE FROM mail_message WHERE model like 'work.task.record';
DELETE FROM mail_message WHERE model like 'product.demand';
DELETE FROM mail_message WHERE model like 'production.plan';
DELETE FROM mail_message WHERE model like 'production.plan_line';
DELETE FROM mail_message WHERE model like 'nt.zy.sale.annual_plan';
DELETE FROM mail_message WHERE model like 'nt.zy.sale.annual_plan_line';
DELETE FROM mail_message WHERE model like 'nt_zy_sale.total_annual_quantity';
DELETE FROM mail_message WHERE model like 'nt_zy_sale.sale_market';
DELETE FROM mail_message WHERE model like 'nt_zy_sale.sale_market_line';
DELETE FROM mail_message WHERE model like 'department.monthly.work';
DELETE FROM contract_code_report;